# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - master
  - release/*
  - develop

variables:
  - group: CommonBuildVariables
  - name: artifactVersion
    value: $(Build.SourceBranchName)-$(build.BuildNumber)
  - name: buildFor
    value: 'nonprod'
  - name: MAVEN_CACHE_FOLDER
    value: $(Pipeline.Workspace)/.m2/repository
  - name: MAVEN_OPTS
    value: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'
  - ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
      - name: buildFor
        value: 'prod'
  - ${{ if ne(variables['Build.SourceBranchName'], 'master') }}:
      - name: buildFor
        value: 'nonprod'
pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories: 
    - repository: PolarisTemplateRepo
      type: github
      name: Maersk-Global/DOT-AzureDevops-CICD-templates
      ref: refs/heads/master 
      endpoint: github.com_azure_pipelines




stages:
  - stage: Build
    displayName: Build and Push Image
    jobs:
      - template: polaris.template.yml@PolarisTemplateRepo
        parameters:
          webAppScan: 'webAppScanFalse'
          polarisScanBranch: 'NA'
          javaVersion: '11'
          replaceTokenFile: 'settings.xml'
      - job: Build
        displayName: Code and Image Build
        dependsOn: Polaris_Scan
        steps:
          - task: MavenAuthenticate@0
            displayName: 'Maven Authenticate'
            inputs:
              artifactsFeeds: 'athena-feed'
              mavenServiceConnections: 'athena-feed-sn'
          - checkout: self
            persistCredentials: true
            clean: true
          - task: Cache@2
            inputs:
              key: 'maven | "$(Agent.OS)" | **/pom.xml'
              restoreKeys: |
                maven | "$(Agent.OS)"
                maven
              path: $(MAVEN_CACHE_FOLDER)
            displayName: Cache Maven local repo
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                echo "Using version: $(artifactVersion)"
                echo "Build for : $(buildFor)"
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m $(MAVEN_OPTS)'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.11'
              jdkArchitectureOption: 'x64'
              goals: 'package'
          - task: CopyFiles@2
            displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
            inputs:
              SourceFolder: '$(system.defaultworkingdirectory)'
              Contents: '**/*'
              TargetFolder: '$(build.artifactstagingdirectory)'
            condition: succeeded()

          - task: CopyFiles@2
            inputs:
              SourceFolder: 'aks/'
              Contents: '**'
              TargetFolder: '$(Build.ArtifactStagingDirectory)/aks'
              OverWrite: true'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact: drop'
            inputs:
              PathtoPublish: '$(build.artifactstagingdirectory)'
              ArtifactName: 'drop'
            condition: succeeded()

          - task: Bash@3
            displayName: Log Build is done
            inputs:
              targetType: 'inline'
              script:
                echo "Maven Build success"

          - task: Bash@3
            displayName: Log sonar is done
            inputs:
              targetType: 'inline'
              script:
                echo "sonar success"

          - task: Bash@3
            condition: and(succeeded(),eq(variables.buildFor, 'prod'))
            displayName: Prod Branch Print Docker image
            inputs:
              targetType: 'inline'
              script:
                echo " ***** Image created at athproductionacr.azurecr.io/athena-currency-conversion-listner:$(build.BuildNumber)"

          - task: Bash@3
            condition: and(succeeded(),eq(variables.buildFor, 'nonprod'))
            displayName: Non prod Branch Print Docker image
            inputs:
              targetType: 'inline'
              script:
                echo " ***** Image created at athtestacr.azurecr.io/athena-currency-conversion-listner:$(build.BuildNumber)"

          - task: Docker@2
            condition: and(succeeded(),eq(variables.buildFor, 'prod'))
            displayName: Login to Prod ACR
            inputs:
              command: login
              containerRegistry: athproductionacr-scn
          - task: Docker@2
            condition: and(succeeded(),eq(variables.buildFor, 'prod'))
            displayName: Master Branch Build and Push Docker Image
            inputs:
              repository: 'athena-currency-conversion-listener'
              containerRegistry: athproductionacr-scn
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: |
                $(artifactVersion)
          - task: Docker@2
            condition: and(succeeded(),eq(variables.buildFor, 'nonprod'))
            displayName: Login to Non Prod ACR
            inputs:
              command: login
              containerRegistry: athtestacr-scn
          - task: Docker@2
            condition: and(succeeded(), eq(variables.buildFor, 'nonprod'))
            displayName: Dev branch Build and Push Docker Image
            inputs:
              repository: 'athena-currency-conversion-listener'
              containerRegistry: athtestacr-scn
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: |
                $(artifactVersion)
          - task: Docker@2
            condition: and(succeeded(), eq(variables.buildFor, 'nonprod'))
            displayName: Logout of Non Prod ACR
            inputs:
              command: logout
              containerRegistry: athtestacr-scn
          - task: Docker@2
            condition: and(succeeded(),eq(variables.buildFor, 'prod'))
            displayName: Logout of Prod ACR
            inputs:
              command: logout
              containerRegistry: athproductionacr-scn

          - task: Bash@3
            displayName: Log Build and Push Docker Image is done
            inputs:
              targetType: 'inline'
              script:
                echo "Build and Push Docker Image success"
